calories_json = {
  "VERDURAS_Y_HORTALIZAS": [
    {"nombre": "Aceitunas negras", "calorias_por_100g": 349},
    {"nombre": "Aceitunas verdes", "calorias_por_100g": 132},
    {"nombre": "Acelgas", "calorias_por_100g": 33},
    {"nombre": "Ajos", "calorias_por_100g": 169},
    {"nombre": "Alcachofas", "calorias_por_100g": 64},
    {"nombre": "Apio", "calorias_por_100g": 20},
    {"nombre": "Berenjena", "calorias_por_100g": 29},
    {"nombre": "Berros", "calorias_por_100g": 21},
    {"nombre": "Brócoli", "calorias_por_100g": 31},
    {"nombre": "Calabacín", "calorias_por_100g": 31},
    {"nombre": "Calabaza", "calorias_por_100g": 24},
    {"nombre": "Cebolla", "calorias_por_100g": 47},
    {"nombre": "Cebolla tierna", "calorias_por_100g": 39},
    {"nombre": "Champiñón y otras setas", "calorias_por_100g": 28},
    {"nombre": "Col", "calorias_por_100g": 28},
    {"nombre": "Col de Bruselas", "calorias_por_100g": 54},
    {"nombre": "Coliflor", "calorias_por_100g": 30},
    {"nombre": "Endibia", "calorias_por_100g": 22},
    {"nombre": "Escarola", "calorias_por_100g": 37},
    {"nombre": "Espárragos", "calorias_por_100g": 26},
    {"nombre": "Espárragos en lata", "calorias_por_100g": 24},
    {"nombre": "Espinaca", "calorias_por_100g": 32},
    {"nombre": "Espinacas congeladas", "calorias_por_100g": 25},
    {"nombre": "Habas tiernas", "calorias_por_100g": 64},
    {"nombre": "Hinojo", "calorias_por_100g": 16},
    {"nombre": "Lechuga", "calorias_por_100g": 18},
    {"nombre": "Nabos", "calorias_por_100g": 29},
    {"nombre": "Papas cocidas", "calorias_por_100g": 86},
    {"nombre": "Pepino", "calorias_por_100g": 12},
    {"nombre": "Perejil", "calorias_por_100g": 55},
    {"nombre": "Pimiento", "calorias_por_100g": 22},
    {"nombre": "Porotos verdes", "calorias_por_100g": 21},
    {"nombre": "Puerros", "calorias_por_100g": 42},
    {"nombre": "Rábanos", "calorias_por_100g": 20},
    {"nombre": "Remolacha", "calorias_por_100g": 40},
    {"nombre": "Repollo", "calorias_por_100g": 19},
    {"nombre": "Rúcula", "calorias_por_100g": 37},
    {"nombre": "Soja, Brotes de", "calorias_por_100g": 50},
    {"nombre": "Tomate triturado en conserva", "calorias_por_100g": 39},
    {"nombre": "Tomates", "calorias_por_100g": 22},
    {"nombre": "Trufa", "calorias_por_100g": 92},
    {"nombre": "Zanahoria", "calorias_por_100g": 42},
    {"nombre": "Zumo de tomate", "calorias_por_100g": 21}
  ],
  "FRUTAS": [
    {"nombre": "Arándanos", "calorias_por_100g": 41},
    {"nombre": "Caqui", "calorias_por_100g": 64},
    {"nombre": "Cereza", "calorias_por_100g": 47},
    {"nombre": "Chirimoya", "calorias_por_100g": 78},
    {"nombre": "Ciruela", "calorias_por_100g": 44},
    {"nombre": "Ciruela seca", "calorias_por_100g": 290},
    {"nombre": "Coco", "calorias_por_100g": 646},
    {"nombre": "Dátil", "calorias_por_100g": 279},
    {"nombre": "Dátil seco", "calorias_por_100g": 306},
    {"nombre": "Frambuesa", "calorias_por_100g": 40},
    {"nombre": "Fresas", "calorias_por_100g": 36},
    {"nombre": "Granada", "calorias_por_100g": 65},
    {"nombre": "Grosella", "calorias_por_100g": 37},
    {"nombre": "Higos", "calorias_por_100g": 80},
    {"nombre": "Higos secos", "calorias_por_100g": 275},
    {"nombre": "Kiwi", "calorias_por_100g": 51},
    {"nombre": "Limón", "calorias_por_100g": 39},
    {"nombre": "Mandarina", "calorias_por_100g": 40},
    {"nombre": "Mango", "calorias_por_100g": 57},
    {"nombre": "Manzana", "calorias_por_100g": 52},
    {"nombre": "Melón", "calorias_por_100g": 31},
    {"nombre": "Mora", "calorias_por_100g": 37},
    {"nombre": "Naranja", "calorias_por_100g": 44},
    {"nombre": "Nectarina", "calorias_por_100g": 64},
    {"nombre": "Nísperos", "calorias_por_100g": 97},
    {"nombre": "Papaya", "calorias_por_100g": 45},
    {"nombre": "Pera", "calorias_por_100g": 61},
    {"nombre": "Piña", "calorias_por_100g": 51},
    {"nombre": "Piña en almíbar", "calorias_por_100g": 84},
    {"nombre": "Plátano", "calorias_por_100g": 90},
    {"nombre": "Pomelo", "calorias_por_100g": 30},
    {"nombre": "Sandía", "calorias_por_100g": 30},
    {"nombre": "Uva", "calorias_por_100g": 81},
    {"nombre": "Uva pasa", "calorias_por_100g": 324},
    {"nombre": "Zumo de fruta", "calorias_por_100g": 45},
    {"nombre": "Zumo de Naranja", "calorias_por_100g": 42}
  ],
  "FRUTOS_SECOS": [
    {"nombre": "Almendras", "calorias_por_100g": 620},
    {"nombre": "Avellanas", "calorias_por_100g": 675},
    {"nombre": "Castañas", "calorias_por_100g": 199},
    {"nombre": "Maní", "calorias_por_100g": 560},
    {"nombre": "Nueces", "calorias_por_100g": 660},
    {"nombre": "Piñones", "calorias_por_100g": 660},
    {"nombre": "Pistacho", "calorias_por_100g": 581}
  ],
  "LÁCTEOS_Y_DERIVADOS": [
    {"nombre": "Cuajada", "calorias_por_100g": 92},
    {"nombre": "Flan de huevo", "calorias_por_100g": 126},
    {"nombre": "Flan de vainilla", "calorias_por_100g": 102},
    {"nombre": "Helados lácteos", "calorias_por_100g": 167},
    {"nombre": "Leche condensada c/azúcar", "calorias_por_100g": 350},
    {"nombre": "Leche condensada s/azúcar", "calorias_por_100g": 160},
    {"nombre": "Leche de cabra", "calorias_por_100g": 72},
    {"nombre": "Leche de oveja", "calorias_por_100g": 96},
    {"nombre": "Leche descremada", "calorias_por_100g": 36},
    {"nombre": "Leche en polvo descremada", "calorias_por_100g": 373},
    {"nombre": "Leche en polvo entera", "calorias_por_100g": 500},
    {"nombre": "Leche entera", "calorias_por_100g": 68},
    {"nombre": "Leche semi descremada", "calorias_por_100g": 49},
    {"nombre": "Mousse", "calorias_por_100g": 177},
    {"nombre": "Nata o crema de leche", "calorias_por_100g": 298},
    {"nombre": "Queso blanco desnatado", "calorias_por_100g": 70},
    {"nombre": "Queso Brie", "calorias_por_100g": 263},
    {"nombre": "Queso cammembert", "calorias_por_100g": 312},
    {"nombre": "Queso cheddar", "calorias_por_100g": 381},
    {"nombre": "Queso crema", "calorias_por_100g": 245},
    {"nombre": "Queso de bola", "calorias_por_100g": 349},
    {"nombre": "Queso de Burgos", "calorias_por_100g": 174},
    {"nombre": "Queso de oveja", "calorias_por_100g": 245},
    {"nombre": "Queso edam", "calorias_por_100g": 306},
    {"nombre": "Queso emmental", "calorias_por_100g": 415},
    {"nombre": "Queso fundido untable", "calorias_por_100g": 285},
    {"nombre": "Queso gruyere", "calorias_por_100g": 391},
    {"nombre": "Queso manchego", "calorias_por_100g": 376},
    {"nombre": "Queso mozzarella", "calorias_por_100g": 245},
    {"nombre": "Queso parmesano", "calorias_por_100g": 393},
    {"nombre": "Queso ricota", "calorias_por_100g": 400},
    {"nombre": "Queso roquefort", "calorias_por_100g": 405},
    {"nombre": "Requesón", "calorias_por_100g": 96},
    {"nombre": "Yogur desnatado", "calorias_por_100g": 45},
    {"nombre": "Yogur desnatado con frutas", "calorias_por_100g": 82},
    {"nombre": "Yogur enriquecido con nata", "calorias_por_100g": 65},
    {"nombre": "Yogur natural", "calorias_por_100g": 62},
    {"nombre": "Yogur natural con fruta", "calorias_por_100g": 100}
  ],
    "CARNES_CAJA_Y_EMBUTIDOS": [
    {"nombre": "Bacon (Panceta ahumada)", "calorias_por_100g": 665},
    {"nombre": "Butifarra cocida", "calorias_por_100g": 390},
    {"nombre": "Butifarra, salchicha fresca", "calorias_por_100g": 326},
    {"nombre": "Cabrito", "calorias_por_100g": 127},
    {"nombre": "Cerdo, chuleta", "calorias_por_100g": 330},
    {"nombre": "Cerdo, hígado", "calorias_por_100g": 153},
    {"nombre": "Cerdo, lomo", "calorias_por_100g": 208},
    {"nombre": "Chicharrón", "calorias_por_100g": 601},
    {"nombre": "Chorizo", "calorias_por_100g": 468},
    {"nombre": "Ciervo", "calorias_por_100g": 120},
    {"nombre": "Codorniz y perdiz", "calorias_por_100g": 114},
    {"nombre": "Conejo, liebre", "calorias_por_100g": 162},
    {"nombre": "Cordero lechón", "calorias_por_100g": 105},
    {"nombre": "Cordero pierna", "calorias_por_100g": 98},
    {"nombre": "Cordero, costillas", "calorias_por_100g": 215},
    {"nombre": "Cordero, hígado", "calorias_por_100g": 132},
    {"nombre": "Faisán", "calorias_por_100g": 144},
    {"nombre": "Foie-Gras", "calorias_por_100g": 518},
    {"nombre": "Gallina", "calorias_por_100g": 369},
    {"nombre": "Hamburguesa", "calorias_por_100g": 230},
    {"nombre": "Jabalí", "calorias_por_100g": 107},
    {"nombre": "Jamón", "calorias_por_100g": 380},
    {"nombre": "Jamón cocido", "calorias_por_100g": 126},
    {"nombre": "Jamón crudo", "calorias_por_100g": 296},
    {"nombre": "Jamón York", "calorias_por_100g": 289},
    {"nombre": "Lengua de vaca", "calorias_por_100g": 191},
    {"nombre": "Lomo embuchado", "calorias_por_100g": 380},
    {"nombre": "Mortadela", "calorias_por_100g": 265},
    {"nombre": "Pato", "calorias_por_100g": 200},
    {"nombre": "Pavo, Muslo", "calorias_por_100g": 186},
    {"nombre": "Pavo, Pechuga", "calorias_por_100g": 134},
    {"nombre": "Perdiz", "calorias_por_100g": 120},
    {"nombre": "Pies de cerdo", "calorias_por_100g": 290},
    {"nombre": "Pollo, Hígado", "calorias_por_100g": 129},
    {"nombre": "Pollo, Muslo", "calorias_por_100g": 186},
    {"nombre": "Pollo", "calorias_por_100g": 134},
    {"nombre": "Salami", "calorias_por_100g": 325},
    {"nombre": "Salchicha Frankfurt", "calorias_por_100g": 315},
    {"nombre": "Salchichón", "calorias_por_100g": 294},
    {"nombre": "Ternera", "calorias_por_100g": 181},
    {"nombre": "Ternera, chuleta", "calorias_por_100g": 168},
    {"nombre": "Ternera, hígado", "calorias_por_100g": 140},
    {"nombre": "Ternera, lengua", "calorias_por_100g": 207},
    {"nombre": "Ternera, riñón", "calorias_por_100g": 86},
    {"nombre": "Ternera, sesos", "calorias_por_100g": 125},
    {"nombre": "Ternera, solomillo", "calorias_por_100g": 290},
    {"nombre": "Tira de asado", "calorias_por_100g": 401},
    {"nombre": "Tripas", "calorias_por_100g": 100},
    {"nombre": "Vacuno, Hígado", "calorias_por_100g": 129}
  ],
   "PESCADOS_Y_MARISCOS": [
    {"nombre": "Atún fresco", "calorias_por_100g": 144},
    {"nombre": "Atún en conserva", "calorias_por_100g": 184},
    {"nombre": "Bacalao fresco", "calorias_por_100g": 82},
    {"nombre": "Bacalao salado", "calorias_por_100g": 290},
    {"nombre": "Calamares", "calorias_por_100g": 92},
    {"nombre": "Camarón cocido", "calorias_por_100g": 99},
    {"nombre": "Langosta", "calorias_por_100g": 77},
    {"nombre": "Mejillones", "calorias_por_100g": 86},
    {"nombre": "Merluza", "calorias_por_100g": 82},
    {"nombre": "Salmón fresco", "calorias_por_100g": 208},
    {"nombre": "Salmón ahumado", "calorias_por_100g": 117},
    {"nombre": "Sardina fresca", "calorias_por_100g": 208},
    {"nombre": "Sardina en conserva", "calorias_por_100g": 208},
    {"nombre": "Trucha", "calorias_por_100g": 148},
    {"nombre": "Vieiras", "calorias_por_100g": 69}
  ],
  "AZÚCARES_Y_DULCES": [
    {"nombre": "Azúcar blanco", "calorias_por_100g": 400},
    {"nombre": "Azúcar moreno", "calorias_por_100g": 380},
    {"nombre": "Chocolate negro", "calorias_por_100g": 545},
    {"nombre": "Chocolate con leche", "calorias_por_100g": 535},
    {"nombre": "Dulce de membrillo", "calorias_por_100g": 290},
    {"nombre": "Miel", "calorias_por_100g": 304},
    {"nombre": "Mermelada", "calorias_por_100g": 250},
    {"nombre": "Caramelo", "calorias_por_100g": 394},
    {"nombre": "Galletas", "calorias_por_100g": 485}
  ],
  "CEREALES_Y_DERIVADOS": [
    {"nombre": "Arroz blanco cocido", "calorias_por_100g": 130},
    {"nombre": "Arroz integral cocido", "calorias_por_100g": 111},
    {"nombre": "Avena", "calorias_por_100g": 389},
    {"nombre": "Pan blanco", "calorias_por_100g": 265},
    {"nombre": "Pan integral", "calorias_por_100g": 247},
    {"nombre": "Harina de trigo", "calorias_por_100g": 364},
    {"nombre": "Pasta cocida", "calorias_por_100g": 158},
    {"nombre": "Galletas integrales", "calorias_por_100g": 416}
  ],
  "LEGUMBRES": [
    {"nombre": "Alubias cocidas", "calorias_por_100g": 127},
    {"nombre": "Garbanzos cocidos", "calorias_por_100g": 164},
    {"nombre": "Lentejas cocidas", "calorias_por_100g": 116},
    {"nombre": "Soja cocida", "calorias_por_100g": 173},
    {"nombre": "Judías verdes cocidas", "calorias_por_100g": 31}
  ],
  "HUEVOS": [
    {"nombre": "Huevo de gallina entero", "calorias_por_100g": 155},
    {"nombre": "Clara de huevo", "calorias_por_100g": 48},
    {"nombre": "Yema de huevo", "calorias_por_100g": 322},
    {"nombre": "Huevo de codorniz", "calorias_por_100g": 158}
  ],
  "PASTELERÍA_Y_REPOSTERÍA": [
    {"nombre": "Bizcocho", "calorias_por_100g": 321},
    {"nombre": "Magdalenas", "calorias_por_100g": 377},
    {"nombre": "Pastel de manzana", "calorias_por_100g": 237},
    {"nombre": "Tarta de queso", "calorias_por_100g": 321},
    {"nombre": "Tarta de chocolate", "calorias_por_100g": 405},
    {"nombre": "Tarta de frutas", "calorias_por_100g": 268},
    {"nombre": "Galletas", "calorias_por_100g": 485}
  ],
  "BEBIDAS": [
    {"nombre": "Agua", "calorias_por_100g": 0},
    {"nombre": "Café solo", "calorias_por_100g": 2},
    {"nombre": "Té", "calorias_por_100g": 1},
    {"nombre": "Cerveza", "calorias_por_100g": 43},
    {"nombre": "Vino tinto", "calorias_por_100g": 85},
    {"nombre": "Vino blanco", "calorias_por_100g": 82},
    {"nombre": "Refrescos", "calorias_por_100g": 42},
    {"nombre": "Zumo de frutas", "calorias_por_100g": 45}
  ],
  "ACEITES_Y_GRASAS": [
    {"nombre": "Aceite de oliva", "calorias_por_100g": 884},
    {"nombre": "Aceite de girasol", "calorias_por_100g": 884},
    {"nombre": "Mantequilla", "calorias_por_100g": 717},
    {"nombre": "Margarina", "calorias_por_100g": 717},
    {"nombre": "Mayonesa", "calorias_por_100g": 680}
  ],
  "SALSAS_Y_CONDIMENTOS": [
    {"nombre": "Mostaza", "calorias_por_100g": 15},
    {"nombre": "Ketchup", "calorias_por_100g": 112},
    {"nombre": "Salsa de soja", "calorias_por_100g": 53},
    {"nombre": "Vinagre", "calorias_por_100g": 3},
    {"nombre": "Salsa bechamel", "calorias_por_100g": 150},
    {"nombre": "Salsa de tomate", "calorias_por_100g": 29}
  ]
}


